#pragma once
#include "../util.h"

enum Instructions : u8 {
    OpExit,
    OpReturn,
    OpPop,
    OpName,
    OpNumber,
    OpByteNumber,
    OpTrue,
    OpFalse,
    OpNone,
    OpAdd,
    OpSubtract,
    OpModulous,
    OpMultiply,
    OpDivide,
    OpExponent,
    OpEqual,
    OpGreater,
    OpLess,
    OpGreaterThanOrEq,
    OpLessThanOrEq,
    OpNot,
    OpNegate,
    OpPrint,
    OpDefineGlobal,
    OpGetGlobal,
    OpSetGlobal,
    OpGetLocal,
    OpSetLocal,
    OpGetProperty,
    OpSetProperty,
    OpGetUpValue,
    OpSetUpValue,
    OpPopLocals,
    OpJump,
    OpJumpBack,
    OpJumpIfTrue,
    OpJumpIfFalse,
    OpJumpPopIfFalse,
    OpFunction,
    OpCall,
    OpType,
    OpInherit,
    OpBindMethod
};
